<a href="https://colab.research.google.com/github/Zahra-Aliyeva/Project-global_terrorism-/blob/main/GTD%20python(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/globalterrorismdb_0718dist.csv (2).zip',encoding="latin1")
df.head()

/tmp/ipython-input-2051427031.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/globalterrorismdb_0718dist.csv (2).zip',encoding="latin1")

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [ ]:
df.isnull().sum()

eventid            0
iyear              0
imonth             0
iday               0
approxdate    172452
               ...
INT_LOG            0
INT_IDEO           0
INT_MISC           0
INT_ANY            0
related       156653
Length: 135, dtype: int64

In [ ]:
(df.isnull().mean() * 100).sort_values(ascending=False)

gsubname3           99.988992
weapsubtype4        99.961473
weapsubtype4_txt    99.961473
weaptype4_txt       99.959822
weaptype4           99.959822
                      ...
dbsource             0.000000
INT_LOG              0.000000
INT_IDEO             0.000000
INT_MISC             0.000000
INT_ANY              0.000000
Length: 135, dtype: float64

In [ ]:
threshold = len(df) * 0.5
df = df.dropna(axis=1, thresh=threshold)

In [ ]:
df = df.dropna(subset=['iyear', 'country_txt'])

In [ ]:
df['nkill'] = df['nkill'].fillna(0)
df['nwound'] = df['nwound'].fillna(0)

In [ ]:
df['city'] = df['city'].fillna('Unknown')

In [ ]:
df.info()
df.isnull().sum().sort_values(ascending=False).head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 58 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   eventid           181691 non-null  int64
 1   iyear             181691 non-null  int64
 2   imonth            181691 non-null  int64
 3   iday              181691 non-null  int64
 4   extended          181691 non-null  int64
 5   country           181691 non-null  int64
 6   country_txt       181691 non-null  object
 7   region            181691 non-null  int64
 8   region_txt        181691 non-null  object
 9   provstate         181270 non-null  object
 10  city              181691 non-null  object
 11  latitude          177135 non-null  float64
 12  longitude         177134 non-null  float64
 13  specificity       181685 non-null  float64
 14  vicinity          181691 non-null  int64
 15  summary           115562 non-null  object
 16  crit1             181691 non-null  int64
 17  crit2             181691 non-null  int64
 18  crit3             181691 non-null  int64
 19  doubtterr         181690 non-null  float64
 20  multiple          181690 non-null  float64
 21  success           181691 non-null  int64
 22  suicide           181691 non-null  int64
 23  attacktype1       181691 non-null  int64
 24  attacktype1_txt   181691 non-null  object
 25  targtype1         181691 non-null  int64
 26  targtype1_txt     181691 non-null  object
 27  targsubtype1      171318 non-null  float64
 28  targsubtype1_txt  171318 non-null  object
 29  corp1             139139 non-null  object
 30  target1           181053 non-null  object
 31  natlty1           180132 non-null  float64
 32  natlty1_txt       180132 non-null  object
 33  gname             181691 non-null  object
 34  guncertain1       181311 non-null  float64
 35  individual        181691 non-null  int64
 36  nperps            110576 non-null  float64
 37  nperpcap          112202 non-null  float64
 38  claimed           115571 non-null  float64
 39  weaptype1         181691 non-null  int64
 40  weaptype1_txt     181691 non-null  object
 41  weapsubtype1      160923 non-null  float64
 42  weapsubtype1_txt  160923 non-null  object
 43  weapdetail        114021 non-null  object
 44  nkill             181691 non-null  float64
 45  nkillus           117245 non-null  float64
 46  nkillter          114733 non-null  float64
 47  nwound            181691 non-null  float64
 48  nwoundus          116989 non-null  float64
 49  nwoundte          112548 non-null  float64
 50  property          181691 non-null  int64
 51  ishostkid         181513 non-null  float64
 52  scite1            115500 non-null  object
 53  dbsource          181691 non-null  object
 54  INT_LOG           181691 non-null  int64
 55  INT_IDEO          181691 non-null  int64
 56  INT_MISC          181691 non-null  int64
 57  INT_ANY           181691 non-null  int64
dtypes: float64(19), int64(22), object(17)
memory usage: 80.4+ MB

nperps        71115
nperpcap      69489
nwoundte      69143
weapdetail    67670
nkillter      66958
scite1        66191
summary       66129
claimed       66120
nwoundus      64702
nkillus       64446
dtype: int64

In [ ]:
cols_to_drop = [
    'nperps', 'nperpcap',
    'weapdetail',
    'scite1',
    'summary','weapsubtype1','targsubtype1','natlty1']

df = df.drop(columns=cols_to_drop)

In [ ]:
fill_zero_cols = [
    'nkillter', 'nkillus',
    'nwoundte', 'nwoundus','claimed','guncertain1','ishostkid']

df[fill_zero_cols] = df[fill_zero_cols].fillna(0)

In [ ]:
fill_unknown_cols=['corp1','weapsubtype1_txt','targsubtype1_txt','natlty1_txt','target1','provstate']
df[fill_unknown_cols]=df[fill_unknown_cols].fillna('Unknown')

In [ ]:
cols_to_drop = [
    'INT_LOG', 'INT_IDEO',
    'INT_MISC',
    'INT_ANY']

df = df.drop(columns=cols_to_drop)

In [ ]:
df_map = df.dropna(subset=['latitude', 'longitude'])

In [ ]:
df = df.dropna(subset=['specificity', 'doubtterr', 'multiple'])

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['eventid'].is_unique

True

In [ ]:
df.isnull().sum().sort_values(ascending=False).head(10)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181683 entries, 0 to 181690
Data columns (total 46 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   eventid           181683 non-null  int64
 1   iyear             181683 non-null  int64
 2   imonth            181683 non-null  int64
 3   iday              181683 non-null  int64
 4   extended          181683 non-null  int64
 5   country           181683 non-null  int64
 6   country_txt       181683 non-null  object
 7   region            181683 non-null  int64
 8   region_txt        181683 non-null  object
 9   provstate         181683 non-null  object
 10  city              181683 non-null  object
 11  latitude          177133 non-null  float64
 12  longitude         177132 non-null  float64
 13  specificity       181683 non-null  float64
 14  vicinity          181683 non-null  int64
 15  crit1             181683 non-null  int64
 16  crit2             181683 non-null  int64
 17  crit3             181683 non-null  int64
 18  doubtterr         181683 non-null  float64
 19  multiple          181683 non-null  float64
 20  success           181683 non-null  int64
 21  suicide           181683 non-null  int64
 22  attacktype1       181683 non-null  int64
 23  attacktype1_txt   181683 non-null  object
 24  targtype1         181683 non-null  int64
 25  targtype1_txt     181683 non-null  object
 26  targsubtype1_txt  181683 non-null  object
 27  corp1             181683 non-null  object
 28  target1           181683 non-null  object
 29  natlty1_txt       181683 non-null  object
 30  gname             181683 non-null  object
 31  guncertain1       181683 non-null  float64
 32  individual        181683 non-null  int64
 33  claimed           181683 non-null  float64
 34  weaptype1         181683 non-null  int64
 35  weaptype1_txt     181683 non-null  object
 36  weapsubtype1_txt  181683 non-null  object
 37  nkill             181683 non-null  float64
 38  nkillus           181683 non-null  float64
 39  nkillter          181683 non-null  float64
 40  nwound            181683 non-null  float64
 41  nwoundus          181683 non-null  float64
 42  nwoundte          181683 non-null  float64
 43  property          181683 non-null  int64
 44  ishostkid         181683 non-null  float64
 45  dbsource          181683 non-null  object
dtypes: float64(14), int64(18), object(14)
memory usage: 65.1+ MB

In [ ]:
df.to_csv('gtd_clean.csv', index=False)

In [ ]:
from google.colab import files

files.download('gtd_clean.csv')